### ISSUE TITLE
[Bug Report] Mod crashes the game

### ISSUE THREAD

**Issue by Samisafool** [jpenilla/mods-command#3]
**Describe the bug**
Minecraft crashing

**To Reproduce**
1. Run minecraft with this mod and fabric api, modmenu

**Expected behavior**
It would work

**Screenshots**

**Environment information:**
 
Either manually fill out the information below, *or* attach a [paste](https://paste.gg/) of the output from running `/dumpmods` or `dumpclientmods`.
 - Operating System: Arch Linux
 - Java Version: 17
 - Java Vendor: JDK from Arch repos
 - Minecraft Version: 1.19.3
 - Mods Command Version: 1.1.0 (Latest)
 - Other Installed Mods: Fabric API, Mod Menu

**Additional context**
https://mclo.gs/4cROvsR

**Comment by jpenilla** [comment]
Fixed in 1.1.1
