### ISSUE TITLE
[Bug Report] Crash

### ISSUE THREAD

**Issue by Nicolol1234** [jpenilla/mods-command#5]
**Describe the bug**
crash when executing command

**To Reproduce**
1. Install the mod
2. run mods command

**Expected behavior**
nothing should happen

**Screenshots**
logs & crash report:

Logs: https://mclo.gs/ZSkWh3a

crash report: https://mclo.gs/IzA5p2H

**Environment information:**
 
Everything is on the logs/crash report

**Additional context**
nothing else

**Comment by jpenilla** [comment]
Is this reproducible with Minecraft 1.20.2 and Mods Command 1.1.4?

**Comment by jpenilla** [comment]
Mods Command 1.1.3 is incompatible with Better Fabric Console 1.1.6, Better Fabric Console 1.1.5 should work, but I don't have time to support old versions of Minecraft and my mods.
